package com.prud.model.middleware;

import java.math.BigDecimal;
import java.math.BigInteger;

public class FundDetails {
     private String fundId;
     private String fundParent;
     private String virtualFundSplitMethod;
     private String percentageOfAmountIndicator;
     private BigDecimal amount01;
     private BigDecimal amount02;
     private BigDecimal amount03;
     private BigDecimal amount04;
     private BigDecimal amount05;
     private BigDecimal amount06;
     private BigDecimal amount07;
     private BigDecimal amount08;
     private BigDecimal amount09;
     private BigDecimal amount10;
     private String unitLinkedFund01;
     private String unitLinkedFund02;
     private String unitLinkedFund03;
     private String unitLinkedFund04;
     private String unitLinkedFund05;
     private String unitLinkedFund06;
     private String unitLinkedFund07;
     private String unitLinkedFund08;
     private String unitLinkedFund09;
     private String unitLinkedFund10;
     private BigDecimal interateRate01;
     private BigInteger renewalMonths01;
     private BigInteger yearsInForce01;
     private BigDecimal interateRate02;
     private BigInteger renewalMonths02;
     private BigInteger yearsInForce02;
     private BigDecimal interateRate03;
     private BigInteger renewalMonths03;
     private BigInteger yearsInForce03;
     private BigDecimal interateRate04;
     private BigInteger renewalMonths04;
     private BigInteger yearsInForce04;
     private BigDecimal interateRate05;
     private BigInteger renewalMonths05;
     private BigInteger yearsInForce05;
     private BigDecimal interateRate06;
     private BigInteger renewalMonths06;
     private BigInteger yearsInForce06;
     private BigDecimal interateRate07;
     private BigInteger renewalMonths07;
     private BigInteger yearsInForce07;
     private BigDecimal interateRate08;
     private BigInteger renewalMonths08;
     private BigInteger yearsInForce08;
     private BigDecimal interateRate09;
     private BigInteger renewalMonths09;
     private BigInteger yearsInForce09;
     private BigDecimal interateRate10;
     private BigInteger renewalMonths10;
     private BigInteger yearsInForce10;
}
