//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.02 at 11:52:18 AM IST 
//

package com.prud.model.il;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.csc.smart/msp/schemas/MSPContext}MSPContext" minOccurs="0"/>
 *         &lt;element name="AGNTSEL">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AGCLS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AGTYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ARACDE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BCMTAB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CLNTSEL">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CURRCODE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DTEAPP">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CCYY">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="4"/>
 *                         &lt;pattern value="((2[0-9][0-9][0-9])|(1[0-9][0-9][0-9])|9999|0)"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MM">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="2"/>
 *                         &lt;pattern value="(([0-9])|(0[0-9])|(1[0-2])|99|0)"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DD">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="2"/>
 *                         &lt;pattern value="(([0-9])|(0[1-9]|[1-2][0-9])|(3[0-1])|99|0)"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EXCAGR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MINSTA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="17"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OCMTAB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OVCPC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PAYFRQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PAYMTH">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RCMTAB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPSEL">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SCMTAB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "mspContext", "agntsel", "agcls", "agtype", "aracde", "bcmtab", "clntsel", "currcode",
		"dteapp", "excagr", "minsta", "ocmtab", "ovcpc", "payfrq", "paymth", "rcmtab", "repsel", "scmtab" })
@XmlRootElement(name = "AGT1CRTI_REC", namespace = "http://www.csc.smart/bo/schemas/AGT1CRTI")
public class AGT1CRTIREC {

	@XmlElement(name = "MSPContext", namespace = "http://www.csc.smart/msp/schemas/MSPContext")
	protected MSPContext mspContext;
	@XmlElement(name = "AGNTSEL", required = true)
	protected String agntsel;
	@XmlElement(name = "AGCLS", required = true)
	protected String agcls;
	@XmlElement(name = "AGTYPE", required = true)
	protected String agtype;
	@XmlElement(name = "ARACDE", required = true)
	protected String aracde;
	@XmlElement(name = "BCMTAB", required = true)
	protected String bcmtab;
	@XmlElement(name = "CLNTSEL", required = true)
	protected String clntsel;
	@XmlElement(name = "CURRCODE", required = true)
	protected String currcode;
	@XmlElement(name = "DTEAPP", required = true)
	protected AGT1CRTIREC.DTEAPP dteapp;
	@XmlElement(name = "EXCAGR", required = true)
	protected String excagr;
	@XmlElement(name = "MINSTA", required = true)
	protected BigDecimal minsta;
	@XmlElement(name = "OCMTAB", required = true)
	protected String ocmtab;
	@XmlElement(name = "OVCPC", required = true)
	protected BigDecimal ovcpc;
	@XmlElement(name = "PAYFRQ", required = true)
	protected String payfrq;
	@XmlElement(name = "PAYMTH", required = true)
	protected String paymth;
	@XmlElement(name = "RCMTAB", required = true)
	protected String rcmtab;
	@XmlElement(name = "REPSEL", required = true)
	protected String repsel;
	@XmlElement(name = "SCMTAB", required = true)
	protected String scmtab;

	/**
	 * Gets the value of the mspContext property.
	 * 
	 * @return possible object is {@link MSPContext }
	 * 
	 */
	public MSPContext getMSPContext() {
		return mspContext;
	}

	/**
	 * Sets the value of the mspContext property.
	 * 
	 * @param value
	 *            allowed object is {@link MSPContext }
	 * 
	 */
	public void setMSPContext(MSPContext value) {
		this.mspContext = value;
	}

	/**
	 * Gets the value of the agntsel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAGNTSEL() {
		return agntsel;
	}

	/**
	 * Sets the value of the agntsel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAGNTSEL(String value) {
		this.agntsel = value;
	}

	/**
	 * Gets the value of the agcls property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAGCLS() {
		return agcls;
	}

	/**
	 * Sets the value of the agcls property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAGCLS(String value) {
		this.agcls = value;
	}

	/**
	 * Gets the value of the agtype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAGTYPE() {
		return agtype;
	}

	/**
	 * Sets the value of the agtype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAGTYPE(String value) {
		this.agtype = value;
	}

	/**
	 * Gets the value of the aracde property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getARACDE() {
		return aracde;
	}

	/**
	 * Sets the value of the aracde property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setARACDE(String value) {
		this.aracde = value;
	}

	/**
	 * Gets the value of the bcmtab property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBCMTAB() {
		return bcmtab;
	}

	/**
	 * Sets the value of the bcmtab property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBCMTAB(String value) {
		this.bcmtab = value;
	}

	/**
	 * Gets the value of the clntsel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCLNTSEL() {
		return clntsel;
	}

	/**
	 * Sets the value of the clntsel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCLNTSEL(String value) {
		this.clntsel = value;
	}

	/**
	 * Gets the value of the currcode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCURRCODE() {
		return currcode;
	}

	/**
	 * Sets the value of the currcode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCURRCODE(String value) {
		this.currcode = value;
	}

	/**
	 * Gets the value of the dteapp property.
	 * 
	 * @return possible object is {@link AGT1CRTIREC.DTEAPP }
	 * 
	 */
	public AGT1CRTIREC.DTEAPP getDTEAPP() {
		return dteapp;
	}

	/**
	 * Sets the value of the dteapp property.
	 * 
	 * @param value
	 *            allowed object is {@link AGT1CRTIREC.DTEAPP }
	 * 
	 */
	public void setDTEAPP(AGT1CRTIREC.DTEAPP value) {
		this.dteapp = value;
	}

	/**
	 * Gets the value of the excagr property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEXCAGR() {
		return excagr;
	}

	/**
	 * Sets the value of the excagr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEXCAGR(String value) {
		this.excagr = value;
	}

	/**
	 * Gets the value of the minsta property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getMINSTA() {
		return minsta;
	}

	/**
	 * Sets the value of the minsta property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setMINSTA(BigDecimal value) {
		this.minsta = value;
	}

	/**
	 * Gets the value of the ocmtab property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOCMTAB() {
		return ocmtab;
	}

	/**
	 * Sets the value of the ocmtab property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOCMTAB(String value) {
		this.ocmtab = value;
	}

	/**
	 * Gets the value of the ovcpc property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getOVCPC() {
		return ovcpc;
	}

	/**
	 * Sets the value of the ovcpc property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setOVCPC(BigDecimal value) {
		this.ovcpc = value;
	}

	/**
	 * Gets the value of the payfrq property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPAYFRQ() {
		return payfrq;
	}

	/**
	 * Sets the value of the payfrq property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPAYFRQ(String value) {
		this.payfrq = value;
	}

	/**
	 * Gets the value of the paymth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPAYMTH() {
		return paymth;
	}

	/**
	 * Sets the value of the paymth property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPAYMTH(String value) {
		this.paymth = value;
	}

	/**
	 * Gets the value of the rcmtab property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRCMTAB() {
		return rcmtab;
	}

	/**
	 * Sets the value of the rcmtab property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRCMTAB(String value) {
		this.rcmtab = value;
	}

	/**
	 * Gets the value of the repsel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getREPSEL() {
		return repsel;
	}

	/**
	 * Sets the value of the repsel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setREPSEL(String value) {
		this.repsel = value;
	}

	/**
	 * Gets the value of the scmtab property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSCMTAB() {
		return scmtab;
	}

	/**
	 * Sets the value of the scmtab property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSCMTAB(String value) {
		this.scmtab = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="CCYY">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
	 *               &lt;totalDigits value="4"/>
	 *               &lt;pattern value="((2[0-9][0-9][0-9])|(1[0-9][0-9][0-9])|9999|0)"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="MM">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
	 *               &lt;totalDigits value="2"/>
	 *               &lt;pattern value="(([0-9])|(0[0-9])|(1[0-2])|99|0)"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="DD">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
	 *               &lt;totalDigits value="2"/>
	 *               &lt;pattern value="(([0-9])|(0[1-9]|[1-2][0-9])|(3[0-1])|99|0)"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "ccyy", "mm", "dd" })
	public static class DTEAPP {

		@XmlElement(name = "CCYY", required = true)
		protected BigInteger ccyy;
		@XmlElement(name = "MM", required = true)
		protected BigInteger mm;
		@XmlElement(name = "DD", required = true)
		protected BigInteger dd;

		/**
		 * Gets the value of the ccyy property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getCCYY() {
			return ccyy;
		}

		/**
		 * Sets the value of the ccyy property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setCCYY(BigInteger value) {
			this.ccyy = value;
		}

		/**
		 * Gets the value of the mm property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getMM() {
			return mm;
		}

		/**
		 * Sets the value of the mm property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setMM(BigInteger value) {
			this.mm = value;
		}

		/**
		 * Gets the value of the dd property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getDD() {
			return dd;
		}

		/**
		 * Sets the value of the dd property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setDD(BigInteger value) {
			this.dd = value;
		}

	}

}
